# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(530, 240)
        Form.setMinimumSize(QtCore.QSize(530, 240))
        Form.setMaximumSize(QtCore.QSize(530, 240))
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(80, 40, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.password = QtWidgets.QTextEdit(Form)
        self.password.setGeometry(QtCore.QRect(150, 90, 251, 41))
        self.password.setObjectName("password")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(80, 90, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.emergency = QtWidgets.QPushButton(Form)
        self.emergency.setGeometry(QtCore.QRect(150, 140, 121, 41))
        self.emergency.setObjectName("emergency")
        self.login = QtWidgets.QPushButton(Form)
        self.login.setGeometry(QtCore.QRect(280, 140, 121, 41))
        self.login.setObjectName("login")
        self.account = QtWidgets.QTextEdit(Form)
        self.account.setGeometry(QtCore.QRect(150, 40, 251, 41))
        self.account.setObjectName("account")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "账号："))
        self.label_2.setText(_translate("Form", "密码："))
        self.emergency.setText(_translate("Form", "应急模式"))
        self.login.setText(_translate("Form", "登录系统"))
